import Head from "next/head";
import { Button } from "../components/Common/Button";
import styles from "@/styles/Home.module.css";

export default function Home() {
	return (
		<>
			<Head>
				<title>Alpha</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				
				{/* <Button styles={styles.button} text="Testing Button" /> */}
			</main>
		</>
	);
}
